In [1]:
import numpy as np

# Глобальное выравнивание

In [2]:
def show_alignment(a, b, DP, gap, mismatch, match):
    s1 = ""
    s2 = ""
    
    i, j = len(a), len(b)
    while (i != 0) & (j != 0):
        if (a[i - 1] == b[j - 1]) & (DP[i, j] == DP[i - 1, j - 1] + match):
            s1 += a[i - 1]
            s2 += b[j - 1]
            i -= 1
            j -= 1
            
        elif (a[i - 1] != b[j - 1]) & (DP[i, j] == DP[i - 1, j - 1] + mismatch):
            s1 += a[i - 1]
            s2 += b[j - 1]
            i -= 1
            j -= 1
            
        elif DP[i, j] == DP[i - 1, j] + gap:
            s1 += a[i - 1]
            s2 += "_"
            i -= 1
            
        else:
            s1 += "_"
            s2 += b[j - 1]
            j -= 1
            
            
    if (i == 0):
        s1 += "_" * j
        s2 += (b[:j])[::-1]
        
    elif (j == 0):
        s1 += (a[:i])[::-1]
        s2 += "_" * i
        
    print(s1[::-1])
    print(s2[::-1])

In [3]:
def alignmentNeedlemanWunsch(a, b, gap=-1, mismatch=-1, match=1):
    DP = np.zeros((len(a) + 1, len(b) + 1))
    
    for i in range(len(a)):
        DP[i + 1, 0] = DP[i, 0] + gap
        
    for j in range(len(b)):
        DP[0, j + 1] = DP[0, j] + gap
        
    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            eps = match if a[i - 1] == b[j - 1] else mismatch
            DP[i, j] = max(DP[i - 1, j] + gap, DP[i, j - 1] + gap, 
                           DP[i - 1, j - 1] + eps)
            
    show_alignment(a, b, DP, gap, mismatch, match)
    
    return DP

In [4]:
def example_test():
    dp = alignmentNeedlemanWunsch("GATTACA", "GCATGCU")
    print(dp)

In [5]:
example_test()

G_ATTACA
GCA_TGCU
[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  0.  0.  1.  0. -1. -2. -3.]
 [-3. -1. -1.  0.  2.  1.  0. -1.]
 [-4. -2. -2. -1.  1.  1.  0. -1.]
 [-5. -3. -3. -1.  0.  0.  0. -1.]
 [-6. -4. -2. -2. -1. -1.  1.  0.]
 [-7. -5. -3. -1. -2. -2.  0.  0.]]


## Тест 1: последовательности одинаковой длины, в глобальном выравнивании которых есть несовпадения и гэпы
## Тест 2: выравнивание последовательностей из теста 1 с измененными штрафами

In [6]:
def test1():
    alignmentNeedlemanWunsch("ACTCG", "AGCCA")

def test2():
    alignmentNeedlemanWunsch("ACTCG", "AGCCA", gap=-0.499)

In [7]:
test1()
print()
test2()

A_CTCG
AGC_CA

A_CTC_G
AGC_CA_
