In [1]:
import numpy as np

# Выравнивание с матрицей весов

In [2]:
def show_alignment_m(a, b, DP, weights, atoi):
    s1 = ""
    s2 = ""
    gap_idx = weights.shape[0] - 1

    
    i, j = len(a), len(b)
    while (i != 0) & (j != 0):
        if DP[i, j] == DP[i - 1, j - 1] + weights[atoi[a[i - 1]], atoi[b[j - 1]]]:
            s1 += a[i - 1]
            s2 += b[j - 1]
            i -= 1
            j -= 1
            
        elif DP[i, j] == DP[i - 1, j] + weights[atoi[a[i - 1]], gap_idx]:
            s1 += a[i - 1]
            s2 += "_"
            i -= 1
            
        else:
            s1 += "_"
            s2 += b[j - 1]
            j -= 1
            
            
    if (i == 0):
        s1 += "_" * j
        s2 += (b[:j])[::-1]
        
    elif (j == 0):
        s1 += (a[:i])[::-1]
        s2 += "_" * i
        
    print(s1[::-1])
    print(s2[::-1])

In [3]:
def alignmentWithMatrix(a, b, weights, atoi):
    # atoi returns index of element of sequence in matrix
    DP = np.zeros((len(a) + 1, len(b) + 1))
    gap_idx = weights.shape[0] - 1
    
    for i in range(len(a)):
        DP[i + 1, 0] = DP[i, 0] + weights[atoi[a[i]], gap_idx]
        
    for j in range(len(b)):
        DP[0, j + 1] = DP[0, j] + weights[atoi[b[j]], gap_idx]
        
    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            DP[i, j] = max(DP[i - 1, j] + weights[atoi[a[i - 1]], gap_idx], 
                           DP[i, j - 1] + weights[atoi[b[j - 1]], gap_idx],
                           DP[i - 1, j - 1] + weights[atoi[a[i - 1]], atoi[b[j - 1]]])
            
    show_alignment_m(a, b, DP, weights, atoi)
    
    return DP

In [4]:
def example_test_wm():
    atoi = {"G": 0, "T": 1, "A": 2, "C": 3, "U": 4}
    matrix = np.full((6, 6), -1)
    for i in range(5):
        matrix[i, i] = 1
    dp = alignmentWithMatrix("GATTACA", "GCATGCU", weights=matrix, atoi=atoi)
    print(dp)

In [5]:
example_test_wm()

G_ATTACA
GCA_TGCU
[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1.  1.  0. -1. -2. -3. -4. -5.]
 [-2.  0.  0.  1.  0. -1. -2. -3.]
 [-3. -1. -1.  0.  2.  1.  0. -1.]
 [-4. -2. -2. -1.  1.  1.  0. -1.]
 [-5. -3. -3. -1.  0.  0.  0. -1.]
 [-6. -4. -2. -2. -1. -1.  1.  0.]
 [-7. -5. -3. -1. -2. -2.  0.  0.]]


## Пример последовательностей и матрицы весов, при изменении одного элемента которой меняется выравнивание

In [6]:
def test1_wm():
    atoi = {"G": 0, "C": 1, "A": 2}
    matrix = np.asarray([[2, -1, -1, -1],
                         [-1, 2, -2, -1],
                         [-3, -2, 2, -1],
                         [-1, -1, -1, -1]])
    alignmentWithMatrix("GGC", "AGA", matrix, atoi)

In [7]:
def test2_wm():
    atoi = {"G": 0, "C": 1, "A": 2}
    matrix = np.asarray([[2, -1, -3, -1],
                         [-1, 2, -2, -1],
                         [-3, -2, 2, -1],
                         [-1, -1, -1, -1]])
    alignmentWithMatrix("GGC", "AGA", matrix, atoi)

In [8]:
test1_wm()
print()
test2_wm()

GGC
AGA

_GGC
A_GA


# Локальное выравнивание

In [9]:
def show_localAlignment(a, b, DP, max_idx, weights, atoi):
    s1 = ""
    s2 = ""
    gap_idx = weights.shape[0] - 1

    
    i, j = max_idx
    while DP[i][j] != 0:
        if DP[i, j] == DP[i - 1, j - 1] + weights[atoi[a[i - 1]], atoi[b[j - 1]]]:
            s1 += a[i - 1].upper()
            s2 += b[j - 1].upper()
            i -= 1
            j -= 1
            
        elif DP[i, j] == DP[i - 1, j] + weights[atoi[a[i - 1]], gap_idx]:
            s1 += a[i - 1].upper()
            s2 += "_"
            i -= 1
            
        else:
            s1 += "_"
            s2 += b[j - 1].upper()
            j -= 1
       
    s1 += (a[:i].lower())[::-1]
    s2 += (b[:j].lower())[::-1]
    
    if i > j:
        s2 += " " * (i - j)
    else:
        s1 += " " * (j - i)
        
    s1 = s1[::-1] + a[max_idx[0]:].lower()
    s2 = s2[::-1] + b[max_idx[1]:].lower()
        
    print(s1)
    print(s2)

In [10]:
def localAlignment(a, b, weights, atoi):
    # atoi returns index of element of sequence in matrix
    DP = np.zeros((len(a) + 1, len(b) + 1))
    gap_idx = weights.shape[0] - 1
    
    for i in range(len(a)):
        DP[i + 1, 0] = 0
        
    for j in range(len(b)):
        DP[0, j + 1] = 0
        
    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            DP[i, j] = max(0,
                           DP[i - 1, j] + weights[atoi[a[i - 1]], gap_idx], 
                           DP[i, j - 1] + weights[atoi[b[j - 1]], gap_idx],
                           DP[i - 1, j - 1] + weights[atoi[a[i - 1]], atoi[b[j - 1]]])
            
    max_idx = np.unravel_index(DP.argmax(), DP.shape)
            
    show_localAlignment(a, b, DP, max_idx, weights, atoi)
    
    return DP

In [11]:
def example_test_la():
    atoi = {"A" : 0, "C" : 1, "T" : 2}
    matrix = np.asarray([[2, -1, -1, -1],
                         [-1, 2, -1, -1],
                         [-1, -1, 2, -1],
                         [-1, -1, -1, -1]])
    
    localAlignment("AT", "CA", weights=matrix, atoi=atoi)

In [12]:
example_test_la()

 At
cA


## Пример последовательностей, для которых локальное и глобальное выравнивание с одинаковой матрицей весов дает разные результаты на участке локального выравнивания

In [13]:
def test1_la():
    atoi = {"A" : 0, "C" : 1, "T" : 2}
    matrix = np.asarray([[2, -1, -1, -1],
                         [-1, 2, -1, -3],
                         [-1, -1, 2, -1],
                         [-1, -1, -1, -1]])
    
    localAlignment("TCATC", "TAC", weights=matrix, atoi=atoi)
    print()
    alignmentWithMatrix("TCATC", "TAC", weights=matrix, atoi=atoi)

In [14]:
test1_la()

T_Catc
TAC

TCATC
T_A_C
